processor-toolbox:
    processors:
      - type: egg-processor
        name: egg
      - type: forward-fftw
        name: fft
      - type: root-spectrogram-writer
        name: writer
      - type: basic-root-writer
        name: one_d_hist
      - type: gaussian-noise-generator
        name: noise_gen
  

    connections:
      - signal: "egg:header"
        slot: "fft:header" 
      - signal: "egg:ts"
        slot: "noise_gen:slice"
      - signal: "noise_gen:slice" 
        slot: "fft:ts-fftw"
      - signal: "fft:fft"
        slot: "one_d_hist:fs-fftw"
      - signal: "fft:fft"
        slot: "one_d_hist:fs-fftw-power-dist"
      - signal: "egg:egg-done"
        slot: "writer:write-file"

    run-queue:
      - egg

egg:
    filename: "test_input.egg"
    egg-reader: egg3
    slice-size: 4096
    number-of-slices: 1 #0 will run thru everything 

fft:
    transform-flag: ESTIMATE

noise_gen:
    mean: 0 #to get a meaningful difference as of oct 1 2024 these values need to be pretty large
    sigma: 0
    

writer:
    output-file: "test_output.root"
    file-flag: recreate
    min-time: 0.0
    max-time: 0.1
    min-freq: 0.0
    max-freq: 100.0e6

one_d_hist:
    output-file: "test_output_hist.root"
    file-flag: recreate
    