processor-toolbox:
    processors:
      - type: egg-processor
        name: egg
      - type: forward-fftw
        name: fft
      - type: gaussian-noise-generator
        name: noise-gen
      - type: convert-to-power
        name: to-ps
      - type: basic-root-writer
        name: writer

    connections:
      - signal: "egg:header"
        slot: "fft:header"
      - signal: "egg:ts"
        slot: "noise-gen:slice"
      - signal: "noise-gen:slice" 
        slot: "fft:ts-fftw"
      - signal: "fft:fft"
        slot: "to-ps:fs-fftw-to-psd" 
      - signal: "to-ps:psd"
        slot: "writer:ps"
      - signal: "egg:ts"
        slot: "writer:ts"

    run-queue:
      - egg

egg:
    filename: "locust_mc_Seed600_Angle90.000000000_Pos0.0040000_Energy18563.251000000.egg"
    egg-reader: egg3
    slice-size: 4096
    number-of-slices: 1

fft:
    transform-flag: ESTIMATE
    
noise-gen:
    mean: 0.0
    noise-floor-psd: 2.2e-13	# Noise power in W/Hz
    seed: 12345

writer:
    output-file: "ps_output_noise.root"
    file-flag: recreate
