var annotated_dup =
[
    [ "Katydid", "namespace_katydid.html", "namespace_katydid" ],
    [ "monarch2", "namespacemonarch2.html", "namespacemonarch2" ],
    [ "monarch3", "namespacemonarch3.html", "namespacemonarch3" ],
    [ "Nymph", "namespace_nymph.html", "namespace_nymph" ],
    [ "scarab", "namespacescarab.html", "namespacescarab" ],
    [ "Data", "struct_data.html", "struct_data" ],
    [ "DataA", "struct_data_a.html", "struct_data_a" ],
    [ "DataB", "struct_data_b.html", "struct_data_b" ],
    [ "DataC", "struct_data_c.html", "struct_data_c" ],
    [ "DataD", "struct_data_d.html", "struct_data_d" ],
    [ "DataE", "struct_data_e.html", "struct_data_e" ],
    [ "DataF", "struct_data_f.html", "struct_data_f" ],
    [ "DataMap", "struct_data_map.html", "struct_data_map" ],
    [ "ESData", "struct_e_s_data.html", "struct_e_s_data" ],
    [ "ESDataA", "struct_e_s_data_a.html", "struct_e_s_data_a" ],
    [ "ESDataB", "struct_e_s_data_b.html", "struct_e_s_data_b" ],
    [ "ESDataC", "struct_e_s_data_c.html", "struct_e_s_data_c" ],
    [ "ESDataD", "struct_e_s_data_d.html", "struct_e_s_data_d" ],
    [ "ESDataE", "struct_e_s_data_e.html", "struct_e_s_data_e" ],
    [ "ESDataF", "struct_e_s_data_f.html", "struct_e_s_data_f" ],
    [ "KDExtensibleStruct", "struct_k_d_extensible_struct.html", "struct_k_d_extensible_struct" ],
    [ "KDExtensibleStructCore", "struct_k_d_extensible_struct_core.html", "struct_k_d_extensible_struct_core" ],
    [ "KTDataSlotOneArg", "class_k_t_data_slot_one_arg.html", null ],
    [ "KTDoneSlot", "class_k_t_done_slot.html", null ],
    [ "Parameters", "struct_parameters.html", "struct_parameters" ],
    [ "Point", "struct_point.html", "struct_point" ],
    [ "PointCloud", "struct_point_cloud.html", "struct_point_cloud" ],
    [ "SpecDataMap", "struct_spec_data_map.html", "struct_spec_data_map" ],
    [ "StringKeyedBundle", "struct_string_keyed_bundle.html", "struct_string_keyed_bundle" ],
    [ "TypeAndStringKeyedBundle", "struct_type_and_string_keyed_bundle.html", "struct_type_and_string_keyed_bundle" ],
    [ "Viewer", "class_viewer.html", "class_viewer" ]
];