var namespace_katydid =
[
    [ "complexpolar", "class_katydid_1_1complexpolar.html", "class_katydid_1_1complexpolar" ],
    [ "complexpolar< double >", "class_katydid_1_1complexpolar_3_01double_01_4.html", "class_katydid_1_1complexpolar_3_01double_01_4" ],
    [ "complexpolar< float >", "class_katydid_1_1complexpolar_3_01float_01_4.html", "class_katydid_1_1complexpolar_3_01float_01_4" ],
    [ "complexpolar< long double >", "class_katydid_1_1complexpolar_3_01long_01double_01_4.html", "class_katydid_1_1complexpolar_3_01long_01double_01_4" ],
    [ "DiscPoint", "struct_katydid_1_1_disc_point.html", "struct_katydid_1_1_disc_point" ],
    [ "Distance", "class_katydid_1_1_distance.html", "class_katydid_1_1_distance" ],
    [ "Euclidean", "class_katydid_1_1_euclidean.html", "class_katydid_1_1_euclidean" ],
    [ "FixedSize", "struct_katydid_1_1_fixed_size.html", null ],
    [ "KT2DPoint", "struct_katydid_1_1_k_t2_d_point.html", "struct_katydid_1_1_k_t2_d_point" ],
    [ "KT2ROOT", "class_katydid_1_1_k_t2_r_o_o_t.html", "class_katydid_1_1_k_t2_r_o_o_t" ],
    [ "KTAmplitudeCounter", "class_katydid_1_1_k_t_amplitude_counter.html", "class_katydid_1_1_k_t_amplitude_counter" ],
    [ "KTAmplitudeDistribution", "class_katydid_1_1_k_t_amplitude_distribution.html", "class_katydid_1_1_k_t_amplitude_distribution" ],
    [ "KTAmplitudeDistributor", "class_katydid_1_1_k_t_amplitude_distributor.html", "class_katydid_1_1_k_t_amplitude_distributor" ],
    [ "KTAnalysisCandidates", "class_katydid_1_1_k_t_analysis_candidates.html", "class_katydid_1_1_k_t_analysis_candidates" ],
    [ "KTAnalyticAssociateData", "class_katydid_1_1_k_t_analytic_associate_data.html", "class_katydid_1_1_k_t_analytic_associate_data" ],
    [ "KTAnalyticAssociator", "class_katydid_1_1_k_t_analytic_associator.html", "class_katydid_1_1_k_t_analytic_associator" ],
    [ "KTAxisProperties", "class_katydid_1_1_k_t_axis_properties.html", "class_katydid_1_1_k_t_axis_properties" ],
    [ "KTAxisProperties< 1 >", "class_katydid_1_1_k_t_axis_properties_3_011_01_4.html", "class_katydid_1_1_k_t_axis_properties_3_011_01_4" ],
    [ "KTBasicASCIITypeWriterTS", "class_katydid_1_1_k_t_basic_a_s_c_i_i_type_writer_t_s.html", "class_katydid_1_1_k_t_basic_a_s_c_i_i_type_writer_t_s" ],
    [ "KTBasicASCIIWriter", "class_katydid_1_1_k_t_basic_a_s_c_i_i_writer.html", "class_katydid_1_1_k_t_basic_a_s_c_i_i_writer" ],
    [ "KTBasicROOTFileWriter", "class_katydid_1_1_k_t_basic_r_o_o_t_file_writer.html", "class_katydid_1_1_k_t_basic_r_o_o_t_file_writer" ],
    [ "KTBasicROOTTypeWriterEventAnalysis", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_event_analysis.html", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_event_analysis" ],
    [ "KTBasicROOTTypeWriterSpectrumAnalysis", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_spectrum_analysis.html", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_spectrum_analysis" ],
    [ "KTBasicROOTTypeWriterTime", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_time.html", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_time" ],
    [ "KTBasicROOTTypeWriterTransform", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_transform.html", "class_katydid_1_1_k_t_basic_r_o_o_t_type_writer_transform" ],
    [ "KTBlackmanHarrisWindow", "class_katydid_1_1_k_t_blackman_harris_window.html", "class_katydid_1_1_k_t_blackman_harris_window" ],
    [ "KTCandidateCleaner", "class_katydid_1_1_k_t_candidate_cleaner.html", "class_katydid_1_1_k_t_candidate_cleaner" ],
    [ "KTCandidateTrackFinder", "class_katydid_1_1_k_t_candidate_track_finder.html", "class_katydid_1_1_k_t_candidate_track_finder" ],
    [ "KTCCResults", "class_katydid_1_1_k_t_c_c_results.html", "class_katydid_1_1_k_t_c_c_results" ],
    [ "KTChannelHeader", "class_katydid_1_1_k_t_channel_header.html", "class_katydid_1_1_k_t_channel_header" ],
    [ "KTCluster1DData", "class_katydid_1_1_k_t_cluster1_d_data.html", "class_katydid_1_1_k_t_cluster1_d_data" ],
    [ "KTCompareCandidates", "class_katydid_1_1_k_t_compare_candidates.html", "class_katydid_1_1_k_t_compare_candidates" ],
    [ "KTConsensusThresholding", "class_katydid_1_1_k_t_consensus_thresholding.html", "class_katydid_1_1_k_t_consensus_thresholding" ],
    [ "KTConvertToPower", "class_katydid_1_1_k_t_convert_to_power.html", "class_katydid_1_1_k_t_convert_to_power" ],
    [ "KTCorrelationData", "class_katydid_1_1_k_t_correlation_data.html", "class_katydid_1_1_k_t_correlation_data" ],
    [ "KTCorrelationTSData", "class_katydid_1_1_k_t_correlation_t_s_data.html", "class_katydid_1_1_k_t_correlation_t_s_data" ],
    [ "KTCorrelator", "class_katydid_1_1_k_t_correlator.html", "class_katydid_1_1_k_t_correlator" ],
    [ "KTCountHistogram", "class_katydid_1_1_k_t_count_histogram.html", "class_katydid_1_1_k_t_count_histogram" ],
    [ "KTCreateKDTree", "class_katydid_1_1_k_t_create_k_d_tree.html", "class_katydid_1_1_k_t_create_k_d_tree" ],
    [ "KTCutable", "class_katydid_1_1_k_t_cutable.html", "class_katydid_1_1_k_t_cutable" ],
    [ "KTCutableArray", "class_katydid_1_1_k_t_cutable_array.html", "class_katydid_1_1_k_t_cutable_array" ],
    [ "KTDAC", "class_katydid_1_1_k_t_d_a_c.html", "class_katydid_1_1_k_t_d_a_c" ],
    [ "KTDataAccumulator", "class_katydid_1_1_k_t_data_accumulator.html", "class_katydid_1_1_k_t_data_accumulator" ],
    [ "KTDataDisplay", "class_katydid_1_1_k_t_data_display.html", "class_katydid_1_1_k_t_data_display" ],
    [ "KTDataTypeDisplaySpectrumAnalysis", "class_katydid_1_1_k_t_data_type_display_spectrum_analysis.html", "class_katydid_1_1_k_t_data_type_display_spectrum_analysis" ],
    [ "KTDataTypeDisplayTime", "class_katydid_1_1_k_t_data_type_display_time.html", "class_katydid_1_1_k_t_data_type_display_time" ],
    [ "KTDataTypeDisplayTransform", "class_katydid_1_1_k_t_data_type_display_transform.html", "class_katydid_1_1_k_t_data_type_display_transform" ],
    [ "KTDBScan", "class_katydid_1_1_k_t_d_b_scan.html", "class_katydid_1_1_k_t_d_b_scan" ],
    [ "KTDBScanEventClustering", "class_katydid_1_1_k_t_d_b_scan_event_clustering.html", "class_katydid_1_1_k_t_d_b_scan_event_clustering" ],
    [ "KTDBScanTrackClustering", "class_katydid_1_1_k_t_d_b_scan_track_clustering.html", "class_katydid_1_1_k_t_d_b_scan_track_clustering" ],
    [ "KTDCOffsetGenerator", "class_katydid_1_1_k_t_d_c_offset_generator.html", "class_katydid_1_1_k_t_d_c_offset_generator" ],
    [ "KTDefaultNBins", "class_katydid_1_1_k_t_default_n_bins.html", "class_katydid_1_1_k_t_default_n_bins" ],
    [ "KTDefaultNBins< 1 >", "class_katydid_1_1_k_t_default_n_bins_3_011_01_4.html", "class_katydid_1_1_k_t_default_n_bins_3_011_01_4" ],
    [ "KTDigitizerTestData", "class_katydid_1_1_k_t_digitizer_test_data.html", "class_katydid_1_1_k_t_digitizer_test_data" ],
    [ "KTDigitizerTests", "class_katydid_1_1_k_t_digitizer_tests.html", "class_katydid_1_1_k_t_digitizer_tests" ],
    [ "KTDiscriminatedPoints1DData", "class_katydid_1_1_k_t_discriminated_points1_d_data.html", "class_katydid_1_1_k_t_discriminated_points1_d_data" ],
    [ "KTDiscriminatedPoints2DData", "class_katydid_1_1_k_t_discriminated_points2_d_data.html", "class_katydid_1_1_k_t_discriminated_points2_d_data" ],
    [ "KTDisplayWindow", "class_katydid_1_1_k_t_display_window.html", "class_katydid_1_1_k_t_display_window" ],
    [ "KTDistanceClustering", "class_katydid_1_1_k_t_distance_clustering.html", "class_katydid_1_1_k_t_distance_clustering" ],
    [ "KTECDF", "class_katydid_1_1_k_t_e_c_d_f.html", "class_katydid_1_1_k_t_e_c_d_f" ],
    [ "KTEgg1Reader", "class_katydid_1_1_k_t_egg1_reader.html", "class_katydid_1_1_k_t_egg1_reader" ],
    [ "KTEgg2Reader", "class_katydid_1_1_k_t_egg2_reader.html", "class_katydid_1_1_k_t_egg2_reader" ],
    [ "KTEgg3Reader", "class_katydid_1_1_k_t_egg3_reader.html", "class_katydid_1_1_k_t_egg3_reader" ],
    [ "KTEggHeader", "class_katydid_1_1_k_t_egg_header.html", "class_katydid_1_1_k_t_egg_header" ],
    [ "KTEggProcessor", "class_katydid_1_1_k_t_egg_processor.html", "class_katydid_1_1_k_t_egg_processor" ],
    [ "KTEggReader", "class_katydid_1_1_k_t_egg_reader.html", "class_katydid_1_1_k_t_egg_reader" ],
    [ "KTEggWriter", "class_katydid_1_1_k_t_egg_writer.html", "class_katydid_1_1_k_t_egg_writer" ],
    [ "KTFFT", "class_katydid_1_1_k_t_f_f_t.html", "class_katydid_1_1_k_t_f_f_t" ],
    [ "KTFFTW", "class_katydid_1_1_k_t_f_f_t_w.html", "class_katydid_1_1_k_t_f_f_t_w" ],
    [ "KTForwardFFTW", "class_katydid_1_1_k_t_forward_f_f_t_w.html", "class_katydid_1_1_k_t_forward_f_f_t_w" ],
    [ "KTFrequencyCandidate", "class_katydid_1_1_k_t_frequency_candidate.html", "class_katydid_1_1_k_t_frequency_candidate" ],
    [ "KTFrequencyCandidateData", "class_katydid_1_1_k_t_frequency_candidate_data.html", "class_katydid_1_1_k_t_frequency_candidate_data" ],
    [ "KTFrequencyCandidateIdentifier", "class_katydid_1_1_k_t_frequency_candidate_identifier.html", "class_katydid_1_1_k_t_frequency_candidate_identifier" ],
    [ "KTFrequencyDomainArray", "class_katydid_1_1_k_t_frequency_domain_array.html", "class_katydid_1_1_k_t_frequency_domain_array" ],
    [ "KTFrequencyDomainArrayData", "class_katydid_1_1_k_t_frequency_domain_array_data.html", "class_katydid_1_1_k_t_frequency_domain_array_data" ],
    [ "KTFrequencySpectrum", "class_katydid_1_1_k_t_frequency_spectrum.html", "class_katydid_1_1_k_t_frequency_spectrum" ],
    [ "KTFrequencySpectrumData", "class_katydid_1_1_k_t_frequency_spectrum_data.html", "class_katydid_1_1_k_t_frequency_spectrum_data" ],
    [ "KTFrequencySpectrumDataFFTW", "class_katydid_1_1_k_t_frequency_spectrum_data_f_f_t_w.html", "class_katydid_1_1_k_t_frequency_spectrum_data_f_f_t_w" ],
    [ "KTFrequencySpectrumDataFFTWCore", "class_katydid_1_1_k_t_frequency_spectrum_data_f_f_t_w_core.html", "class_katydid_1_1_k_t_frequency_spectrum_data_f_f_t_w_core" ],
    [ "KTFrequencySpectrumDataPolar", "class_katydid_1_1_k_t_frequency_spectrum_data_polar.html", "class_katydid_1_1_k_t_frequency_spectrum_data_polar" ],
    [ "KTFrequencySpectrumDataPolarCore", "class_katydid_1_1_k_t_frequency_spectrum_data_polar_core.html", "class_katydid_1_1_k_t_frequency_spectrum_data_polar_core" ],
    [ "KTFrequencySpectrumFFTW", "class_katydid_1_1_k_t_frequency_spectrum_f_f_t_w.html", "class_katydid_1_1_k_t_frequency_spectrum_f_f_t_w" ],
    [ "KTFrequencySpectrumPolar", "class_katydid_1_1_k_t_frequency_spectrum_polar.html", "class_katydid_1_1_k_t_frequency_spectrum_polar" ],
    [ "KTGainNormalization", "class_katydid_1_1_k_t_gain_normalization.html", "class_katydid_1_1_k_t_gain_normalization" ],
    [ "KTGainVarChi2Data", "class_katydid_1_1_k_t_gain_var_chi2_data.html", "class_katydid_1_1_k_t_gain_var_chi2_data" ],
    [ "KTGainVarChi2Test", "class_katydid_1_1_k_t_gain_var_chi2_test.html", "class_katydid_1_1_k_t_gain_var_chi2_test" ],
    [ "KTGainVariationData", "class_katydid_1_1_k_t_gain_variation_data.html", "class_katydid_1_1_k_t_gain_variation_data" ],
    [ "KTGainVariationProcessor", "class_katydid_1_1_k_t_gain_variation_processor.html", "class_katydid_1_1_k_t_gain_variation_processor" ],
    [ "KTGaussianNoiseGenerator", "class_katydid_1_1_k_t_gaussian_noise_generator.html", "class_katydid_1_1_k_t_gaussian_noise_generator" ],
    [ "KTGlobalRNGEngine", "class_katydid_1_1_k_t_global_r_n_g_engine.html", "class_katydid_1_1_k_t_global_r_n_g_engine" ],
    [ "KTHammingWindow", "class_katydid_1_1_k_t_hamming_window.html", "class_katydid_1_1_k_t_hamming_window" ],
    [ "KTHannWindow", "class_katydid_1_1_k_t_hann_window.html", "class_katydid_1_1_k_t_hann_window" ],
    [ "KTHDF5TypeWriterEventAnalysis", "class_katydid_1_1_k_t_h_d_f5_type_writer_event_analysis.html", "class_katydid_1_1_k_t_h_d_f5_type_writer_event_analysis" ],
    [ "KTHDF5TypeWriterSpectrumAnalysis", "class_katydid_1_1_k_t_h_d_f5_type_writer_spectrum_analysis.html", "class_katydid_1_1_k_t_h_d_f5_type_writer_spectrum_analysis" ],
    [ "KTHDF5TypeWriterTime", "class_katydid_1_1_k_t_h_d_f5_type_writer_time.html", "class_katydid_1_1_k_t_h_d_f5_type_writer_time" ],
    [ "KTHDF5TypeWriterTransform", "class_katydid_1_1_k_t_h_d_f5_type_writer_transform.html", "class_katydid_1_1_k_t_h_d_f5_type_writer_transform" ],
    [ "KTHDF5Writer", "class_katydid_1_1_k_t_h_d_f5_writer.html", "class_katydid_1_1_k_t_h_d_f5_writer" ],
    [ "KTHoughData", "class_katydid_1_1_k_t_hough_data.html", "class_katydid_1_1_k_t_hough_data" ],
    [ "KTHoughTransform", "class_katydid_1_1_k_t_hough_transform.html", "class_katydid_1_1_k_t_hough_transform" ],
    [ "KTImpulseAnalysis", "class_katydid_1_1_k_t_impulse_analysis.html", "class_katydid_1_1_k_t_impulse_analysis" ],
    [ "KTJSONMaker", "class_katydid_1_1_k_t_j_s_o_n_maker.html", "class_katydid_1_1_k_t_j_s_o_n_maker" ],
    [ "KTJSONMakerCompact", "class_katydid_1_1_k_t_j_s_o_n_maker_compact.html", "class_katydid_1_1_k_t_j_s_o_n_maker_compact" ],
    [ "KTJSONMakerPretty", "class_katydid_1_1_k_t_j_s_o_n_maker_pretty.html", "class_katydid_1_1_k_t_j_s_o_n_maker_pretty" ],
    [ "KTJSONTypeWriterEvaluation", "class_katydid_1_1_k_t_j_s_o_n_type_writer_evaluation.html", "class_katydid_1_1_k_t_j_s_o_n_type_writer_evaluation" ],
    [ "KTJSONTypeWriterEventAnalysis", "class_katydid_1_1_k_t_j_s_o_n_type_writer_event_analysis.html", "class_katydid_1_1_k_t_j_s_o_n_type_writer_event_analysis" ],
    [ "KTJSONTypeWriterTime", "class_katydid_1_1_k_t_j_s_o_n_type_writer_time.html", "class_katydid_1_1_k_t_j_s_o_n_type_writer_time" ],
    [ "KTJSONWriter", "class_katydid_1_1_k_t_j_s_o_n_writer.html", "class_katydid_1_1_k_t_j_s_o_n_writer" ],
    [ "KTKDTreeData", "class_katydid_1_1_k_t_k_d_tree_data.html", "class_katydid_1_1_k_t_k_d_tree_data" ],
    [ "KTLinearDensityProbeFit", "class_katydid_1_1_k_t_linear_density_probe_fit.html", "class_katydid_1_1_k_t_linear_density_probe_fit" ],
    [ "KTLinearFitResult", "class_katydid_1_1_k_t_linear_fit_result.html", "class_katydid_1_1_k_t_linear_fit_result" ],
    [ "KTMantis", "class_katydid_1_1_k_t_mantis.html", "class_katydid_1_1_k_t_mantis" ],
    [ "KTMantisClientConfig", "class_katydid_1_1_k_t_mantis_client_config.html", "class_katydid_1_1_k_t_mantis_client_config" ],
    [ "KTMantisClientWriting", "class_katydid_1_1_k_t_mantis_client_writing.html", "class_katydid_1_1_k_t_mantis_client_writing" ],
    [ "KTMantisWriterToTS", "class_katydid_1_1_k_t_mantis_writer_to_t_s.html", "class_katydid_1_1_k_t_mantis_writer_to_t_s" ],
    [ "KTMaskedArray", "class_katydid_1_1_k_t_masked_array.html", "class_katydid_1_1_k_t_masked_array" ],
    [ "KTMCTruthEvents", "class_katydid_1_1_k_t_m_c_truth_events.html", "class_katydid_1_1_k_t_m_c_truth_events" ],
    [ "KTMergeKDTree", "class_katydid_1_1_k_t_merge_k_d_tree.html", "class_katydid_1_1_k_t_merge_k_d_tree" ],
    [ "KTMEROOTTypeWriterBase", "class_katydid_1_1_k_t_m_e_r_o_o_t_type_writer_base.html", "class_katydid_1_1_k_t_m_e_r_o_o_t_type_writer_base" ],
    [ "KTMultiFileJSONReader", "class_katydid_1_1_k_t_multi_file_j_s_o_n_reader.html", "class_katydid_1_1_k_t_multi_file_j_s_o_n_reader" ],
    [ "KTMultiFileROOTTreeReader", "class_katydid_1_1_k_t_multi_file_r_o_o_t_tree_reader.html", "class_katydid_1_1_k_t_multi_file_r_o_o_t_tree_reader" ],
    [ "KTMultiFSDataFFTW", "class_katydid_1_1_k_t_multi_f_s_data_f_f_t_w.html", "class_katydid_1_1_k_t_multi_f_s_data_f_f_t_w" ],
    [ "KTMultiFSDataFFTWCore", "class_katydid_1_1_k_t_multi_f_s_data_f_f_t_w_core.html", "class_katydid_1_1_k_t_multi_f_s_data_f_f_t_w_core" ],
    [ "KTMultiFSDataPolar", "class_katydid_1_1_k_t_multi_f_s_data_polar.html", "class_katydid_1_1_k_t_multi_f_s_data_polar" ],
    [ "KTMultiFSDataPolarCore", "class_katydid_1_1_k_t_multi_f_s_data_polar_core.html", "class_katydid_1_1_k_t_multi_f_s_data_polar_core" ],
    [ "KTMultiPeakEventBuilder", "class_katydid_1_1_k_t_multi_peak_event_builder.html", "class_katydid_1_1_k_t_multi_peak_event_builder" ],
    [ "KTMultiSliceClustering", "class_katydid_1_1_k_t_multi_slice_clustering.html", "class_katydid_1_1_k_t_multi_slice_clustering" ],
    [ "KTMultiSliceROOTTypeWriterSpectrumAnalysis", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_spectrum_analysis.html", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_spectrum_analysis" ],
    [ "KTMultiSliceROOTTypeWriterTime", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_time.html", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_time" ],
    [ "KTMultiSliceROOTTypeWriterTransform", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_transform.html", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_type_writer_transform" ],
    [ "KTMultiSliceROOTWriter", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_writer.html", "class_katydid_1_1_k_t_multi_slice_r_o_o_t_writer" ],
    [ "KTMultiTrackEventData", "class_katydid_1_1_k_t_multi_track_event_data.html", "class_katydid_1_1_k_t_multi_track_event_data" ],
    [ "KTNBinsFunctor", "class_katydid_1_1_k_t_n_bins_functor.html", "class_katydid_1_1_k_t_n_bins_functor" ],
    [ "KTNBinsFunctor< 1 >", "class_katydid_1_1_k_t_n_bins_functor_3_011_01_4.html", "class_katydid_1_1_k_t_n_bins_functor_3_011_01_4" ],
    [ "KTNBinsInArray", "class_katydid_1_1_k_t_n_bins_in_array.html", "class_katydid_1_1_k_t_n_bins_in_array" ],
    [ "KTNBinsInArray< 1, FixedSize >", "class_katydid_1_1_k_t_n_bins_in_array_3_011_00_01_fixed_size_01_4.html", "class_katydid_1_1_k_t_n_bins_in_array_3_011_00_01_fixed_size_01_4" ],
    [ "KTNBinsInArray< 1, XArrayType >", "class_katydid_1_1_k_t_n_bins_in_array_3_011_00_01_x_array_type_01_4.html", "class_katydid_1_1_k_t_n_bins_in_array_3_011_00_01_x_array_type_01_4" ],
    [ "KTNBinsInArray< NDims, FixedSize >", "class_katydid_1_1_k_t_n_bins_in_array_3_01_n_dims_00_01_fixed_size_01_4.html", "class_katydid_1_1_k_t_n_bins_in_array_3_01_n_dims_00_01_fixed_size_01_4" ],
    [ "KTNNFilter", "class_katydid_1_1_k_t_n_n_filter.html", "class_katydid_1_1_k_t_n_n_filter" ],
    [ "KTNormalizedFSDataFFTW", "class_katydid_1_1_k_t_normalized_f_s_data_f_f_t_w.html", "class_katydid_1_1_k_t_normalized_f_s_data_f_f_t_w" ],
    [ "KTNormalizedFSDataPolar", "class_katydid_1_1_k_t_normalized_f_s_data_polar.html", "class_katydid_1_1_k_t_normalized_f_s_data_polar" ],
    [ "KTNormalizedPSData", "class_katydid_1_1_k_t_normalized_p_s_data.html", "class_katydid_1_1_k_t_normalized_p_s_data" ],
    [ "KTOfficialCandidatesWriter", "class_katydid_1_1_k_t_official_candidates_writer.html", "class_katydid_1_1_k_t_official_candidates_writer" ],
    [ "KTPairCompare", "struct_katydid_1_1_k_t_pair_compare.html", "struct_katydid_1_1_k_t_pair_compare" ],
    [ "KTPhysicalArray", "class_katydid_1_1_k_t_physical_array.html", "class_katydid_1_1_k_t_physical_array" ],
    [ "KTPhysicalArray< 1, fftw_complex >", "class_katydid_1_1_k_t_physical_array_3_011_00_01fftw__complex_01_4.html", "class_katydid_1_1_k_t_physical_array_3_011_00_01fftw__complex_01_4" ],
    [ "KTPhysicalArray< 1, XDataType >", "class_katydid_1_1_k_t_physical_array_3_011_00_01_x_data_type_01_4.html", "class_katydid_1_1_k_t_physical_array_3_011_00_01_x_data_type_01_4" ],
    [ "KTPhysicalArray< 2, XDataType >", "class_katydid_1_1_k_t_physical_array_3_012_00_01_x_data_type_01_4.html", "class_katydid_1_1_k_t_physical_array_3_012_00_01_x_data_type_01_4" ],
    [ "KTPointCloud", "struct_katydid_1_1_k_t_point_cloud.html", "struct_katydid_1_1_k_t_point_cloud" ],
    [ "KTPolyphaseFilterBank", "class_katydid_1_1_k_t_polyphase_filter_bank.html", "class_katydid_1_1_k_t_polyphase_filter_bank" ],
    [ "KTPowerSpectrum", "class_katydid_1_1_k_t_power_spectrum.html", "class_katydid_1_1_k_t_power_spectrum" ],
    [ "KTPowerSpectrumData", "class_katydid_1_1_k_t_power_spectrum_data.html", "class_katydid_1_1_k_t_power_spectrum_data" ],
    [ "KTPowerSpectrumDataCore", "class_katydid_1_1_k_t_power_spectrum_data_core.html", "class_katydid_1_1_k_t_power_spectrum_data_core" ],
    [ "KTPowerSpectrumUncertaintyData", "class_katydid_1_1_k_t_power_spectrum_uncertainty_data.html", "class_katydid_1_1_k_t_power_spectrum_uncertainty_data" ],
    [ "KTProcessedTrackData", "class_katydid_1_1_k_t_processed_track_data.html", "class_katydid_1_1_k_t_processed_track_data" ],
    [ "KTProcSummary", "class_katydid_1_1_k_t_proc_summary.html", "class_katydid_1_1_k_t_proc_summary" ],
    [ "KTPSCollectionData", "class_katydid_1_1_k_t_p_s_collection_data.html", "class_katydid_1_1_k_t_p_s_collection_data" ],
    [ "KTRawTimeSeries", "class_katydid_1_1_k_t_raw_time_series.html", "class_katydid_1_1_k_t_raw_time_series" ],
    [ "KTRawTimeSeriesData", "class_katydid_1_1_k_t_raw_time_series_data.html", "class_katydid_1_1_k_t_raw_time_series_data" ],
    [ "KTRectangularWindow", "class_katydid_1_1_k_t_rectangular_window.html", "class_katydid_1_1_k_t_rectangular_window" ],
    [ "KTReverseFFTW", "class_katydid_1_1_k_t_reverse_f_f_t_w.html", "class_katydid_1_1_k_t_reverse_f_f_t_w" ],
    [ "KTRNGChiSquared", "struct_katydid_1_1_k_t_r_n_g_chi_squared.html", "struct_katydid_1_1_k_t_r_n_g_chi_squared" ],
    [ "KTRNGDistribution", "class_katydid_1_1_k_t_r_n_g_distribution.html", "class_katydid_1_1_k_t_r_n_g_distribution" ],
    [ "KTRNGEngine", "class_katydid_1_1_k_t_r_n_g_engine.html", "class_katydid_1_1_k_t_r_n_g_engine" ],
    [ "KTRNGExponential", "struct_katydid_1_1_k_t_r_n_g_exponential.html", "struct_katydid_1_1_k_t_r_n_g_exponential" ],
    [ "KTRNGGaussian", "struct_katydid_1_1_k_t_r_n_g_gaussian.html", "struct_katydid_1_1_k_t_r_n_g_gaussian" ],
    [ "KTRNGPoisson", "struct_katydid_1_1_k_t_r_n_g_poisson.html", "struct_katydid_1_1_k_t_r_n_g_poisson" ],
    [ "KTRNGUniform", "struct_katydid_1_1_k_t_r_n_g_uniform.html", "struct_katydid_1_1_k_t_r_n_g_uniform" ],
    [ "KTRNGUniform01", "struct_katydid_1_1_k_t_r_n_g_uniform01.html", "struct_katydid_1_1_k_t_r_n_g_uniform01" ],
    [ "KTRootGuiLoop", "class_katydid_1_1_k_t_root_gui_loop.html", "class_katydid_1_1_k_t_root_gui_loop" ],
    [ "KTROOTSpectrogramTypeWriter", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_type_writer.html", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_type_writer" ],
    [ "KTROOTSpectrogramTypeWriterTransform", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_type_writer_transform.html", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_type_writer_transform" ],
    [ "KTROOTSpectrogramWriter", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_writer.html", "class_katydid_1_1_k_t_r_o_o_t_spectrogram_writer" ],
    [ "KTROOTTreeTypeWriterEvaluation", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_evaluation.html", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_evaluation" ],
    [ "KTROOTTreeTypeWriterEventAnalysis", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_event_analysis.html", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_event_analysis" ],
    [ "KTROOTTreeTypeWriterSpectrumAnalysis", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_spectrum_analysis.html", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_spectrum_analysis" ],
    [ "KTROOTTreeTypeWriterTime", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_time.html", "class_katydid_1_1_k_t_r_o_o_t_tree_type_writer_time" ],
    [ "KTROOTTreeWriter", "class_katydid_1_1_k_t_r_o_o_t_tree_writer.html", "class_katydid_1_1_k_t_r_o_o_t_tree_writer" ],
    [ "KTRQProcessor", "class_katydid_1_1_k_t_r_q_processor.html", "class_katydid_1_1_k_t_r_q_processor" ],
    [ "KTRSAMatReader", "class_katydid_1_1_k_t_r_s_a_mat_reader.html", "class_katydid_1_1_k_t_r_s_a_mat_reader" ],
    [ "KTRunLoop", "class_katydid_1_1_k_t_run_loop.html", "class_katydid_1_1_k_t_run_loop" ],
    [ "KTSetupLoop", "class_katydid_1_1_k_t_setup_loop.html", "class_katydid_1_1_k_t_setup_loop" ],
    [ "KTSincWindow", "class_katydid_1_1_k_t_sinc_window.html", "class_katydid_1_1_k_t_sinc_window" ],
    [ "KTSingleChannelDAC", "class_katydid_1_1_k_t_single_channel_d_a_c.html", "class_katydid_1_1_k_t_single_channel_d_a_c" ],
    [ "KTSinusoidGenerator", "class_katydid_1_1_k_t_sinusoid_generator.html", "class_katydid_1_1_k_t_sinusoid_generator" ],
    [ "KTSliceHeader", "class_katydid_1_1_k_t_slice_header.html", "class_katydid_1_1_k_t_slice_header" ],
    [ "KTSmooth", "class_katydid_1_1_k_t_smooth.html", "class_katydid_1_1_k_t_smooth" ],
    [ "KTSparseDistanceMatrix", "struct_katydid_1_1_k_t_sparse_distance_matrix.html", "struct_katydid_1_1_k_t_sparse_distance_matrix" ],
    [ "KTSparseWaterfallCandidateData", "class_katydid_1_1_k_t_sparse_waterfall_candidate_data.html", "class_katydid_1_1_k_t_sparse_waterfall_candidate_data" ],
    [ "KTSpectrogramCollector", "class_katydid_1_1_k_t_spectrogram_collector.html", "class_katydid_1_1_k_t_spectrogram_collector" ],
    [ "KTSpectrumDiscriminator", "class_katydid_1_1_k_t_spectrum_discriminator.html", "class_katydid_1_1_k_t_spectrum_discriminator" ],
    [ "KTSpline", "class_katydid_1_1_k_t_spline.html", "class_katydid_1_1_k_t_spline" ],
    [ "KTSwitchFFTWPolar", "class_katydid_1_1_k_t_switch_f_f_t_w_polar.html", "class_katydid_1_1_k_t_switch_f_f_t_w_polar" ],
    [ "KTSymmetricDistanceMatrix", "struct_katydid_1_1_k_t_symmetric_distance_matrix.html", "struct_katydid_1_1_k_t_symmetric_distance_matrix" ],
    [ "KTTerminalTypeWriterTime", "class_katydid_1_1_k_t_terminal_type_writer_time.html", "class_katydid_1_1_k_t_terminal_type_writer_time" ],
    [ "KTTerminalWriter", "class_katydid_1_1_k_t_terminal_writer.html", "class_katydid_1_1_k_t_terminal_writer" ],
    [ "KTTimeFrequency", "class_katydid_1_1_k_t_time_frequency.html", "class_katydid_1_1_k_t_time_frequency" ],
    [ "KTTimeFrequencyDataPolar", "class_katydid_1_1_k_t_time_frequency_data_polar.html", "class_katydid_1_1_k_t_time_frequency_data_polar" ],
    [ "KTTimeFrequencyDataPolarCore", "class_katydid_1_1_k_t_time_frequency_data_polar_core.html", "class_katydid_1_1_k_t_time_frequency_data_polar_core" ],
    [ "KTTimeFrequencyPolar", "class_katydid_1_1_k_t_time_frequency_polar.html", "class_katydid_1_1_k_t_time_frequency_polar" ],
    [ "KTTimeSeries", "class_katydid_1_1_k_t_time_series.html", "class_katydid_1_1_k_t_time_series" ],
    [ "KTTimeSeriesData", "class_katydid_1_1_k_t_time_series_data.html", "class_katydid_1_1_k_t_time_series_data" ],
    [ "KTTimeSeriesDataCore", "class_katydid_1_1_k_t_time_series_data_core.html", "class_katydid_1_1_k_t_time_series_data_core" ],
    [ "KTTimeSeriesDist", "class_katydid_1_1_k_t_time_series_dist.html", "class_katydid_1_1_k_t_time_series_dist" ],
    [ "KTTimeSeriesDistData", "class_katydid_1_1_k_t_time_series_dist_data.html", "class_katydid_1_1_k_t_time_series_dist_data" ],
    [ "KTTimeSeriesFFTW", "class_katydid_1_1_k_t_time_series_f_f_t_w.html", "class_katydid_1_1_k_t_time_series_f_f_t_w" ],
    [ "KTTimeSeriesReal", "class_katydid_1_1_k_t_time_series_real.html", "class_katydid_1_1_k_t_time_series_real" ],
    [ "KTTrackProcessing", "class_katydid_1_1_k_t_track_processing.html", "class_katydid_1_1_k_t_track_processing" ],
    [ "KTTreeIndex", "struct_katydid_1_1_k_t_tree_index.html", "struct_katydid_1_1_k_t_tree_index" ],
    [ "KTTreeIndexEuclidean", "struct_katydid_1_1_k_t_tree_index_euclidean.html", "struct_katydid_1_1_k_t_tree_index_euclidean" ],
    [ "KTTreeIndexManhattan", "struct_katydid_1_1_k_t_tree_index_manhattan.html", "struct_katydid_1_1_k_t_tree_index_manhattan" ],
    [ "KTTSGenerator", "class_katydid_1_1_k_t_t_s_generator.html", "class_katydid_1_1_k_t_t_s_generator" ],
    [ "KTVariableSpectrumDiscriminator", "class_katydid_1_1_k_t_variable_spectrum_discriminator.html", "class_katydid_1_1_k_t_variable_spectrum_discriminator" ],
    [ "KTVarTypePhysicalArray", "class_katydid_1_1_k_t_var_type_physical_array.html", "class_katydid_1_1_k_t_var_type_physical_array" ],
    [ "KTVTPATypeInfo", "struct_katydid_1_1_k_t_v_t_p_a_type_info.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info" ],
    [ "KTVTPATypeInfo< double >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01double_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01double_01_4" ],
    [ "KTVTPATypeInfo< float >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01float_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01float_01_4" ],
    [ "KTVTPATypeInfo< int16_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int16__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int16__t_01_4" ],
    [ "KTVTPATypeInfo< int32_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int32__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int32__t_01_4" ],
    [ "KTVTPATypeInfo< int64_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int64__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int64__t_01_4" ],
    [ "KTVTPATypeInfo< int8_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int8__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01int8__t_01_4" ],
    [ "KTVTPATypeInfo< uint16_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint16__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint16__t_01_4" ],
    [ "KTVTPATypeInfo< uint32_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint32__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint32__t_01_4" ],
    [ "KTVTPATypeInfo< uint64_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint64__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint64__t_01_4" ],
    [ "KTVTPATypeInfo< uint8_t >", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint8__t_01_4.html", "struct_katydid_1_1_k_t_v_t_p_a_type_info_3_01uint8__t_01_4" ],
    [ "KTWaterfallCandidateData", "class_katydid_1_1_k_t_waterfall_candidate_data.html", "class_katydid_1_1_k_t_waterfall_candidate_data" ],
    [ "KTWignerVille", "class_katydid_1_1_k_t_wigner_ville.html", "class_katydid_1_1_k_t_wigner_ville" ],
    [ "KTWignerVilleData", "class_katydid_1_1_k_t_wigner_ville_data.html", "class_katydid_1_1_k_t_wigner_ville_data" ],
    [ "KTWindower", "class_katydid_1_1_k_t_windower.html", "class_katydid_1_1_k_t_windower" ],
    [ "KTWindowFunction", "class_katydid_1_1_k_t_window_function.html", "class_katydid_1_1_k_t_window_function" ],
    [ "KTWV2DData", "class_katydid_1_1_k_t_w_v2_d_data.html", "class_katydid_1_1_k_t_w_v2_d_data" ],
    [ "Manhattan", "class_katydid_1_1_manhattan.html", "class_katydid_1_1_manhattan" ],
    [ "MTEData", "struct_katydid_1_1_m_t_e_data.html", "struct_katydid_1_1_m_t_e_data" ],
    [ "MTRComp", "struct_katydid_1_1_m_t_r_comp.html", "struct_katydid_1_1_m_t_r_comp" ],
    [ "MultiPeakTrackRef", "struct_katydid_1_1_multi_peak_track_ref.html", "struct_katydid_1_1_multi_peak_track_ref" ],
    [ "PTData", "struct_katydid_1_1_p_t_data.html", "struct_katydid_1_1_p_t_data" ],
    [ "TAmplitudeDistributionData", "struct_katydid_1_1_t_amplitude_distribution_data.html", "struct_katydid_1_1_t_amplitude_distribution_data" ],
    [ "TCCLocustMC", "struct_katydid_1_1_t_c_c_locust_m_c.html", "struct_katydid_1_1_t_c_c_locust_m_c" ],
    [ "TChannelHeader", "struct_katydid_1_1_t_channel_header.html", "struct_katydid_1_1_t_channel_header" ],
    [ "TDiscriminatedPoints1DData", "struct_katydid_1_1_t_discriminated_points1_d_data.html", "struct_katydid_1_1_t_discriminated_points1_d_data" ],
    [ "TEggHeader", "struct_katydid_1_1_t_egg_header.html", "struct_katydid_1_1_t_egg_header" ],
    [ "TFrequencyCandidateData", "struct_katydid_1_1_t_frequency_candidate_data.html", "struct_katydid_1_1_t_frequency_candidate_data" ],
    [ "THoughData", "struct_katydid_1_1_t_hough_data.html", "struct_katydid_1_1_t_hough_data" ],
    [ "TKDTreePointData", "struct_katydid_1_1_t_k_d_tree_point_data.html", "struct_katydid_1_1_t_k_d_tree_point_data" ],
    [ "TLinearFitResultData", "struct_katydid_1_1_t_linear_fit_result_data.html", "struct_katydid_1_1_t_linear_fit_result_data" ],
    [ "TMultiTrackEventData", "class_katydid_1_1_t_multi_track_event_data.html", "class_katydid_1_1_t_multi_track_event_data" ],
    [ "TProcessedTrackData", "class_katydid_1_1_t_processed_track_data.html", "class_katydid_1_1_t_processed_track_data" ],
    [ "TrackDistance", "class_katydid_1_1_track_distance.html", "class_katydid_1_1_track_distance" ],
    [ "TrackSetCItComp", "struct_katydid_1_1_track_set_c_it_comp.html", "struct_katydid_1_1_track_set_c_it_comp" ],
    [ "TrackTimeComp", "struct_katydid_1_1_track_time_comp.html", "struct_katydid_1_1_track_time_comp" ],
    [ "TSparseWaterfallCandidateData", "struct_katydid_1_1_t_sparse_waterfall_candidate_data.html", "struct_katydid_1_1_t_sparse_waterfall_candidate_data" ],
    [ "TWaterfallCandidateData", "struct_katydid_1_1_t_waterfall_candidate_data.html", "struct_katydid_1_1_t_waterfall_candidate_data" ]
];