
name: Docs

on:

  push:
    branches: [ main, develop]
    tags: ['v*.*.*']
    
    workflow_dispatch:
  
jobs:

  doc:

    name: Build documentation
  
    runs-on: ubuntu-latest
  
    steps:
    
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            tree \
            doxygen \
            python3-sphinx \
            graphviz
          pip install sphinxcontrib-blockdiag
          pip install sphinxcontrib-contentui
      
      - name: Build docs
        run: |
          cd Documentation
          sphinx-build -M html . build --color
